FROM ktydkrdtr.eogresources.com/dev/ms-centosora:latest
MAINTAINER Sai Dheeraj Devineni

RUN mkdir -p /app/tests
WORKDIR /app/tests
COPY . /app/tests/
RUN pip3.6 install -r requirements.txt

CMD ["pytest"]
