version: "3"
services:
  randomizer:
    image: dheeru/randomizer:v_${TAG}
    deploy:
      replicas: 2 
    entrypoint: python app.py
    ports:
      - "5056:80"
  example:
    image: dheeru/randomizer:v_${TAG}
    deploy:
      replicas: 2
    entrypoint: python app1.py  
    ports:
      - "5067:80"    
